### ISSUE TITLE
Reviews for code packages?

### ISSUE THREAD

**Issue by HeroicNate** [Haacked/feedback#100]
I've been primarily a web designer with actionscript experience and I'm just getting started for the first time in Visual Studio and a project I am trying to do needs a NuGet/GitHub package.

Are there any reviews on packages that let you know whether people have found the packages good, broken, or malicious? I find it very hard to get info on this sort of thing and most people are not interested in helping. All I can find are issue lists, but those aren't exactly reviews. Is there any sort of peer review when it comes to code packages?

**Comment by Haacked** [comment]
There are currently no reviews. For NuGet packages, the download counts is about the only thing you have. That and using Google to search the package URL or package name.
