### ISSUE TITLE
QCON Rio de Janeiro

### ISSUE THREAD

**Issue by ElemarJR** [Haacked/feedback#101]
Hello Phil. How are you doing?

My name is Elemar Junior. I am a brazilian Microsoft .net MVP and also organizer of QCon Rio and SP.

I would like to invite you to speak at Qcon. Especially with your background, have you here would be awesome. What do you think?

The conference will be in August 24 to 28th. 

The conference is really good, with great speakers and the top Brazilian developers attending.

So, what you say? Interested? If yes, could you send me a couple of themes you would be interested on speaking? The only request we have is to have a talk that is different than others you made in previous conferences. We don't want to give the attendees the same talks they can find online.

Best regards

email me at elemarjr@gmail.com

**Comment by Haacked** [comment]
Hi Elemar,

Thank you for the invitation. I would very much love to visit Rio and
speak, but I have a conflict and cannot make those dates. Do keep me in
mind for next year though! I'll try to keep that time free. :)

Phil
