### ISSUE TITLE
Getting server's MAC address or Host IP using ASP.NET 5 (MVC 6)

### ISSUE THREAD

**Issue by csunali** [Haacked/feedback#102]
Hi there,

I would like to ask if you have ever come across to a case where you would need to access either the MAC address or the host IP address of a web server that is running your MVC 6 code, for licensing the web app. 

It was pretty easy using the previous versions of .NET. 

I would really appreciate any help you can provide.

Best regards

Update 1: IIS Application Id would be nice to reach as well. E.g.: "/W3SVC/2"

Update 2: I was able to debug and find some "protected" properties where I can reach at least the IIS application Id, however, I don't think it is a good idea to get my hands dirty with using Reflection.

**Comment by Haacked** [comment]
Seems like a good question to post to StackOverflow.com
