### ISSUE TITLE
Keynote speaking opportunity at .NET Unboxed

### ISSUE THREAD

**Issue by eatdrinksleepcode** [Haacked/feedback#105]
Hi Phil,

I am one of the organizers of the .NET Unboxed conference in Dallas, Texas this fall and I would love for you to be a keynote speaker. The conference was inspired by the energy and excitement around open source on the .NET Core GitHub projects and others, as well as at .NET Fringe in April (where I heard you speak on the social aspects of modern open source development). We want to provide another forum for passionate open source .NET developers to learn from and feed off of each other. Your experience contributing to and advocating for .NET open source from both inside and outside of Microsoft gives you an invaluable perspective on the present and future of .NET open source development.

We have been looking at October 26-27 and November 9-10 as the dates for the conference, depending on the schedules of our keynote speakers. We would love to count you among them.

Thanks for your time.

**Comment by Haacked** [comment]
Hi @eatdrinksleepcode hmm, not sure I can commit to anything yet. Could you tell me more about the conference though?

**Comment by eatdrinksleepcode** [comment]
Sure. We are planning on two speaker tracks for two days. Our primary speaker candidates are active maintainers of .NET open source projects, and secondarily anyone who has contributed or is currently contributing to open source projects on any platform. One of the goals of the conference is to be a conduit through which .NET developers can learn about the wide variety of open source projects that are available for them to use, and as such many of the talks will be about the current status of particular projects. But another significant goal is to encourage more developers to get involved in open source, and to raise the profile of .NET open source in general. So we will also be encouraging our speakers not only to talk about their projects, but also about their experiences in open source, what has worked and what hasn't, what they would do differently, what they see for the future of their project and for .NET open source in general, and particularly, how other developers can get involved. We are also looking for keynote speakers to talk specifically about these topics.

I am happy to answer any other questions you have. We would love to have you there!

**Comment by Haacked** [comment]
I don't think I'll be able to do it, but I can check with other people on my team if you'd like.
