### ISSUE TITLE
good to see there are still people with talent out there

### ISSUE THREAD

**Issue by deverejohn** [Haacked/feedback#106]
just surfing the web, ended up here... wanted to say how nice it is that there are still some talented people out there.. not referring to you, I just needed somewhere to post this. 
thanks... 
john

**Comment by deverejohn** [comment]
I was obviously kidding about that last part. I ended up on github's site looking for some info.. Saw employees pics.. Yours stood out as someone with a 90% Chance of genius; saw your profile, went to your blog since I lived on lake sammamish for 20 years; saw you have a sense of humor, can write AND have style.   Easy to read, no yellow text on a blue background...no sidebars jumping all over the place. U know..   
We're expecting nothing less than absolute greatness from you in the future.
John

**Comment by Haacked** [comment]
Thanks!
