### ISSUE TITLE
RouteMagic redirection giving 404 instead of redirecting

### ISSUE THREAD

**Issue by MrYossu** [Haacked/feedback#107]
Hello,

I have rewritten an old WebForms site in MVC, and want to add permanent redirection from the old URLs to the new. Reading your blog post about RouteMagic (http://haacked.com/archive/2011/02/02/redirecting-routes-to-maintain-persistent-urls.aspx/), I thought this would do the trick.

I added the NuGet package, and then added the following to the end of the RegisterRoutes() method in the RouteConfig class...

routes.Redirect(r => r.MapRoute("old", "Default.aspx")).To(routes.MapRoute("new", "Home"));

However, if I try to access http://localhost:8109/Default.aspx, I just get a 404 in the browser. It doesn't redirect at all.

What am I doing wrong? This is a brand new, out-of-the box MVC project. I just added your package and the one line of code shown above.

Thanks for any help you can give.

**Comment by Haacked** [comment]
Please post this question on the RouteMagic repository: https://github.com/haacked/routemagic

Let me know what version of ASP.NET MVC you created.

**Comment by MrYossu** [comment]
Hello,

Thanks for the reply. I've posted it here...

https://github.com/Haacked/RouteMagic/issues/14

As mentioned there, I'm using MVC5

Thanks again
