### ISSUE TITLE
Code snippet license enquiry

### ISSUE THREAD

**Issue by ncnewman** [Haacked/feedback#110]
Dear Phil,
    I work for IBM and we are considering using a code snippet from your web page article http://haacked.com/archive/2010/04/15/sending-json-to-an-asp-net-mvc-action-method-argument.aspx, but we would like to understand what license it can be taken under.

The code snippet is

protected void Application_Start() 
{ 
 RegisterRoutes(RouteTable.Routes); 
 ValueProviderFactories.Factories.Add(new JsonValueProviderFactory()); 
} 

I don't see any explicit license associated with this snippet, only the reference at bottom of the web page which indicates the license as 'Copyright © 2015 - Phil Haack Blog content licensed under the Creative Commons CC BY 2.5'

Would you grant IBM to use the code snippet under a BSD license?

Kind regards, 
Craig Newman

**Comment by Haacked** [comment]
Absolutely! I think I'll clarify that in my footer.

**Comment by Haacked** [comment]
FYI, I added a note to my footer that all code samples are licensed under the MIT license. But I'm fine with licensing that snippet under the BSD as well. The two are similar enough.

I only mention it in case you see the footer. I didn't want you to get confused.

**Comment by ncnewman** [comment]
Many Thanks for you help. 
Kind regards Craig
