### ISSUE TITLE
Where can I find .NET Stack Wag?

### ISSUE THREAD

**Issue by TheRealJZ** [Haacked/feedback#111]
Hey Phil,

I'm looking to pimp out my laptop and office with swag about how awesome the .NET web stack is, but am having trouble finding anything other than the visual studio logo.  Where can I find some killer swag to brag about our tech stack?

Cheers,
-Z.

**Comment by Haacked** [comment]
Well, you need to hook yourself up with some GitHub stickers: https://github.myshopify.com/products/octodex-sticker-packs

And you can go here for some .NET stickers: https://www.stickermule.com/user/1070667147/stickers
