### ISSUE TITLE
Where does one submit GitHub Desktop issues - too high file list control?

### ISSUE THREAD

**Issue by litera** [Haacked/feedback#112]
Hey Steve.

I couldn't find any better place to contact you, so I'm posting this issue I found in GH Desktop (4Win) here.

The issue is related to invalid scrolling (or better yet invalid control height) that hides some items behod commit details control. If **changes** list is longger than the vertical space it has, items get hidden below underneath commit message/details control. Scrolling to changes list to the bottom keeps a few items invisible that one can only navigate to using keyboard.

Here's an image that shows the problem:
![image](https://cloud.githubusercontent.com/assets/800583/9273426/f09fabae-428c-11e5-8b4e-feb75f454ff2.png)

If you have any questions, let me know and I'll provide additional info if possible.

**Comment by hahmed** [comment]
+1 I have the same issue too on GH4Desktop, just never had the time to let someone know.

With all issues I think they expect an email to support@github.com they then route the email to the correct team.

**Comment by Haacked** [comment]
Yes, please use the contact form to submit issues. github.com/contact

**Comment by litera** [comment]
Thanks Phil. Did so.
