### ISSUE TITLE
Moving Views to custom locations

### ISSUE THREAD

**Issue by angelok1** [Haacked/feedback#114]
Hi Phil,

I just wanted to run something by you and get your thoughts.

I have some views that I want move to a different folder, or maybe drive... essentially making a plug-in architecture with loose view files. The approach (which I'm open to changing) I have taken is to create a custom razor view engine and a virtual path provider. The engine maps the virtual path to the right plugin folder, then the virtual path provider gets the file.

The problem I am running into is that the virtual path provider is properly indicating that the files exist (by looking in the right place), but GetFile isn't being called for them (it's called for other files, like global.asax and other views). 

I have read a TON of stuff on this... and I just don't think I'm clear on how all the parts work... for example, what calls GetFile and under what circumstances?

Any thoughts would be appreciated... I've been banging my head against the wall on this issue for a while...

**Comment by Haacked** [comment]
I wonder if you're running into a caching issue. Did you override `GetCacheDependency`?

**Comment by angelok1** [comment]
I did, and I return null. Is that what I should be doing?

**Comment by angelok1** [comment]
Also, just tried this with the same results:

        public override CacheDependency GetCacheDependency(string virtualPath, System.Collections.IEnumerable virtualPathDependencies, DateTime utcStart)
        {
            if (IsPlugin(virtualPath))
            {
                return null;
            }
            return Previous.GetCacheDependency(virtualPath, virtualPathDependencies, utcStart);
        }

        public override String GetFileHash(String virtualPath, System.Collections.IEnumerable virtualPathDependencies)
        {
            if (IsPlugin(virtualPath))
            {
                return Guid.NewGuid().ToString();
            }

            return Previous.GetFileHash(virtualPath, virtualPathDependencies);
        }

**Comment by Haacked** [comment]
Hmm, that's odd. Try implemeting the [`IViewLocationExpander`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/IViewLocationExpander.cs)

It could be that the view is also being located elsewhere?

**Comment by angelok1** [comment]
I implemented a custom view engine that looks in a virtual "plugins" folder... that seems to work because I can catch that properly in the FileExists method of the VirtualPathProvider and check the physical location ("C:\test")... the "plugins" folder doesn't actually exist, so I can't see it being located unless I told it that I want it to look in "C:\test" for the views (which is what I want the GetFile method to do... but, is never called)...

Thanks again for your insight.
