### ISSUE TITLE
Question about WebViewPages

### ISSUE THREAD

**Issue by kuebelkasten** [Haacked/feedback#115]
Dear Phil,

I just red your article [here](http://haacked.com/archive/2011/02/21/changing-base-type-of-a-razor-view.aspx/) as I'm looking for a solution or a clear NO!-statement to my question posted at [stackoverflow.com](http://stackoverflow.com/questions/32356823/custom-webviewpage-with-additional-type-parameter).
I really think there must be any kind of solution. But this one may be too deep inside of ASP.NET/MVC. But I just need a clear answer as this is driving me mad.
So, if anyone nows, it must be you I guess ;)

If you need more details just let me know. 

Best regards,
Steve

**Comment by Haacked** [comment]
I responded on the SO issue.
