### ISSUE TITLE
RestSharp

### ISSUE THREAD

**Issue by paulallenbright** [Haacked/feedback#117]
Sorry to bother you, but I'm new to Rest Calls and I want to try to use Office365 with RestSharp.   Do you have or know where I can find some example c# calls to make request to Outlook just to pull the root folders.    Once I see an example I think I should be good to go.   Thanks and again sorry to bother.

Best Regards
Paul Bright

**Comment by Haacked** [comment]
Go to https://github.com/restsharp/RestSharp and scroll down to the README. It has some code examples.

**Comment by paulallenbright** [comment]
Thank you sir....
