### ISSUE TITLE
Storing Settings in extension

### ISSUE THREAD

**Issue by carlioth** [Haacked/feedback#118]
Hi! 

Had a look at your excellent article about VS extension settings (http://haacked.com/archive/2014/07/30/visual-studios-extensions-settings/)

Big thanks for the code at github aswell. I'm running into an problem I'm stuck with and hoping that you might have an idea. 
My problem is that I'm not able to grab the SVsServiceProvider by doing an implementation like you. 

What differs in my project is that i have a toolwindow extension and you're using an optionpage. I'm implementing this in VS 2015. 

If I set an breakpoint in the constructor it will never hit. I also tried the old [import] and tried accessing it, but with no luck! 
My class looks like this: 
[Export(typeof(ISettings))]
    class Settings : ISettings
    {
        [Import]
        public IServiceProvider ServiceProvider { get; set; }

        [ImportingConstructor]
        public Settings(IServiceProvider vsServiceProvider)
        {
            var shellSettingsManager = new ShellSettingsManager(vsServiceProvider);
            var writableSettingsStore = shellSettingsManager.GetWritableSettingsStore(SettingsScope.UserSettings);
        }

        public string ViewFilename { get { return _ViewFilename; } set { _ViewFilename = value; } }
        private string _ViewFilename = "hej";
    }

    internal interface ISettings
    {
        string ViewFilename { get; set; }

    }

**Comment by Haacked** [comment]
Seems like this would be better posted as a question on https://stackoverflow.com. Post the link here and I'll either look at it, or ping someone who knows far more than me about it. :smile:
