### ISSUE TITLE
I have a question about a previous project

### ISSUE THREAD

**Issue by jeuvin** [Haacked/feedback#119]
I found SubText online, and I noticed that the project has been abandon for quite some time. I want to update it and make some changes to it. I was going to start a blogging engine on my own but I saw your template and I thought why not try it. Can you tell me if this is open source  and if I can adapt changes to it without any repercussions. I am not intending to sell this product I just want to hack it up and take out the stuff that's not needed and pretty much convert it to a modern mvc and angular project.

**Comment by Haacked** [comment]
Yup! It's open source and on GitHub: https://github.com/Haacked/Subtext

You are right, it is [effectively abandoned](http://haacked.com/archive/2013/12/02/dr-jekyll-and-mr-haack/). However you have every right to fork it, do whatever you want with the fork. Sell it. Don't sell it. Modernize it. Go to town! I look forward to seeing what you do! :smile:

**Comment by jeuvin** [comment]
Can you give me a hint on how to get this thing to run. I got all the
assemblies in place and its error free finally. I just can't get the
project to start. Do I need to publish it or does it run as a web app?

Thanks.

*Jose M. Euvin*
*Senior Software Engineer*
*euvin3582@gmail.com <euvin3582@gmail.com>*

**Comment by jeuvin** [comment]
Never mind, I figured out what was wrong with the project. I'm working in
Vs. 2015 and it doesn't load the same way it might have 2008.

*Jose M. Euvin*
*Senior Software Engineer*
*euvin3582@gmail.com <euvin3582@gmail.com>*
