### ISSUE TITLE
Still having tons of issues

### ISSUE THREAD

**Issue by euvin3582** [Haacked/feedback#121]
I forked your project and updated everything to VS 2015. I'm just not sure how to get the project to run on IIS. I can get it to run when I hit the play button in VS but that does not fix my issue. I want to publish to IIS and run it from there. Can you give me a clue to what I need to do to get it to work.

Thanks.

My Fork
https://github.com/jeuvin/Subtext

**Comment by haacked** [comment]
Sorry, I no longer work on Subtext.
