### ISSUE TITLE
GitHub and CriticMarkup

### ISSUE THREAD

**Issue by DavidBoike** [Haacked/feedback#123]
Hi Phil,

I work for [Particular Software](http://particular.net/) (We make NServiceBus, a .NET service bus) and we do *everything* in GitHub. That includes editing textual content, such as for our company blog, and involves all our employees, both technical and non-technical. I am the facilitator for the 

The reviewing tools within GitHub are not awesome for paragraph based content, since there are a whole lot of words within a "line". Our non-technical employees especially would prefer a Word/GoogleDocs style track changes system. Line comments that can become invalidated by subsequent commits do not work well.

Yet, we publish with Markdown, so we wouldn't want to go to Google Docs - we'd like to be as close to the output as possible.

So, have you ever heard of [CriticMarkup](http://criticmarkup.com/)? It uses a specialized markup within Markdown to show additions, deletions, and comments, directly in context.

In my wildest dreams, GitHub would have an alternative editor for Markdown files that did some limited Markdown formatting during edit (like https://stackedit.io) and also included a full track changes experience, storing the information as CriticMarkup as a full commit.

So, what do you think of my wildest dreams?

Thanks,
David Boike

**Comment by Haacked** [comment]
That does look pretty neat. The best way to provide feedback for github.com is to send it to support@github.com though.
