### ISSUE TITLE
ASP.NET Routing Debugger

### ISSUE THREAD

**Issue by ChefIT** [Haacked/feedback#124]
Hello,

your “Route Tester” is a very good and useful tool. I was able to improve it a bit so it can now display the correct sets for route-constraints and –DataTokens as well as the route's name from the RouteCollection.

I have attached a screenshot and the sources.

Best regards

Wlady/InterTrend
[RouteTester.zip](https://github.com/Haacked/feedback/files/74118/RouteTester.zip)
![routetester](https://cloud.githubusercontent.com/assets/14928951/12037719/f55424fa-ae51-11e5-88e5-67c7e996f35a.jpg)

**Comment by Haacked** [comment]
:cool: Would you be willing to submit your changes as a Pull Request to https://github.com/Haacked/RouteMagic?

**Comment by interTrend** [comment]
Hi,

it is done and looks so:



I have create your RouteDebugger independend from RouteMagic and have 
include it (with the new RouteBasics) in my project to test it:




Thank you for this excelent tool and

Best Regards

Wladimir

Am 08.01.2016 um 21:11 schrieb Phil Haack:
>
> :cool: Would you be willing to submit your changes as a Pull Request 
> to https://github.com/Haacked/RouteMagic?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Haacked/feedback/issues/124#issuecomment-170110943>.
>

-- 
interTrend Software GmbH
Mozartstraße 18
68161 Mannheim

Tel.:    06 21 / 15 60 233
Fax:    06 21 / 15 60 235
e-mail: info@intertrend.net <mailto:info@intertrend.net>

Geschäftsführung: Dr.-Ing. Wladimir Drentschew

Amtsgericht Mannheim:   HRB 6977

UstNr DE 181 398 340
