### ISSUE TITLE
"Evolutionary" framework for building web apps, created in C#

### ISSUE THREAD

**Issue by polterguy** [Haacked/feedback#125]
Howdy Phil,

Wow, didn't realise you're one of the guys behind GitHub. Nice move. Gotta admit I think I like your new employer better ... ;)

Anyway, I've got this entirely new way of creating web apps, which I'd love to have some of the "industry leaders" give me feedback about. You can check out the architectural overview here;

https://www.youtube.com/watch?v=rXbeWSQ07Eo

And of course, I assume you're capable to figure out where I store the goods ... ;)

Anyway, you being one of the seniors of our industry, I'd love if you could check it out a little bit, maybe provide feedback, and hopefully even write some words about it ...

Have a nice new year's eve :)

Thomas Hansen

**Comment by Haacked** [comment]
Hi @polterguy, thanks for sharing! I don't really have time to review it thoroughly, but I thought it looked interesting. :smile:
