### ISSUE TITLE
github

### ISSUE THREAD

**Issue by lantimilan** [Haacked/feedback#126]
I come across your blog when searching for email validator regex. A rather pleasant surprise, I found you are a dad, which I am, and works for a cool place, github. Is there a public place to check out more on working for github and what teams/projects are in the Bellevue area?

I am currently working for a software company in Kirkland and I have a github account for my personal use.

**Comment by Haacked** [comment]
Hi @lantimilan, GitHub job postings are up on https://jobs.lever.co/github/.
