### ISSUE TITLE
Concerning latest update to GitHub Desktop

### ISSUE THREAD

**Issue by Sschlenker** [Haacked/feedback#127]
I am hoping you may have some information that can point me into the right direction.  I recently updated my GitHub Desktop clients to the latest stable builds and now my ssh-agent in my command line tool of choice is not working as it used to. (cmder)

Posh-git that comes with Github still works fine, but what happens now is that if I run Start-SshAgent in either cmder or ConsoleZ (followed your blog post on this one) it will tell me that it is already running.  So then I try ssh-add my private key and it loads the identity and asks for my passphrase. All great except it is still asking for the passphrase each and every time I do a push which never used to happen and does not happen if using posh-git.

Any ideas why this would be happening?

**Comment by Haacked** [comment]
Hi @Sschlenker, I'm not sure why that would happen. Could you email support@github.com and we'll try and help you out? Thanks!
