### ISSUE TITLE
Machu Picchu

### ISSUE THREAD

**Issue by stevejgordon** [Haacked/feedback#128]
Hi Phil,

I heard you on dot net rocks during my commute yesterday and you mentioned you were heading to Peru and hopefully Machu Picchu. My wife and I spent three weeks in Peru last year and it was absolutely amazing. Machu Picchu was high on our list and we did the 5 day Salkantay trek which was tough but breath taking.

I'm sure Richard gave you more advice as it sounded like he'd been to Peru before but I thought I'd drop you a note with a few bits of personal advice in case it's useful.

I recommend getting up early to head up to Machu Picchu as early as possible. If you're staying in Aguas Calientes the night before that gives you the best option to wake up early for the buses to the site. Our trip up was part of our trekking package and we were in the queue for the buses at just before 5am. The line was already building. The first bus sets off at 5:30am and gets you to the top about 30 minutes later. Once at the top you must queue again to present your entry ticket so the earlier you are there the better. We got in not too long after 6:15am and it was well worth it. The sun was just poking rays over the surrounding mountains and the site was wonderfully lit. Also as it was a little quieter we got some wonderful photographs without many people in the frame.

With regards to entry tickets for the site. You need to purchase those in advance. Again ours were part of our trek booked months in advance. I believe you can order them in advance and I do recommend it since they limit numbers each day. We saw lots of people queuing at the Machu Picchu office in Cusco and a few days ahead they seemed to be able to get tickets.

If you want an extra while you are at the site you can optionally purchase passes for either the Machu Picchu Mountain or Huayna Picchu. We did the former and it was a fairly tough climb mostly up steep rock steps for about 1.5 hours. However it's well worth the view from the top. Huayna Picchu is the preferred one to climb but sells out quicker and also is a bit more hairy if you don't like heights. My wife has a bit of vertigo so we gave that a miss. Again, book your tickets in advance if you want a pass.

The site itself is incredible. We actually visited two days in a row (once in a lifetime chance). Two days was about perfect as the first day included a tour from our trek guide for about 2 hours. It was well worth having it since so much can be missed without some local knowledge. If you're heading there under your own steam there are many guides you can privately hire inside the site. They are all licensed I believe. I'd recommend it to get an understanding of what you're looking at as you go around.

We went around the site in the morning with our guide and then decided to walk up to the sun gate. It's included as part of your ticket and if you're okay was a bit of a walk very worthwhile. You get great views of the site as you head up the route. I can't remember how long it took us there and back but it was probably close to 2 hours with some breaks along the way. We got back to the site mid-afternoon and it was much quieter. People seem to do the morning and then head off for trains out of Aguas Calientes. If you can spare the time, try to hang around for the afternoon as you can wander the site with very few tourists around you. We saw large sections with only a couple of other people nearby so it was more relaxed. Also the afternoon light is very nice for photographs.

There are a few other points of interest marked on the map you get. The Inca Bridge was good to see and is a short walk around the side of the mountain. We did that on our second day, along with the climb up Machu Picchu Mountain. I doubt we could have seen all the areas we saw in one day.

Besides that long ramble, I agree with Richard that acclimatising in Cusco for a few days prior is worth doing. We were fortunately no badly affected by altitude. However it was still good to build up a tolerance to walking with less oxygen in the air. Cusco is beautiful and worth some time spent there. We drank the coca tea and also had some natural altitude sickness tablets with us and perhaps those helped us. The worst we had was a bit of a headache on the first day of our trek. You will be breathless walking around for the first few days though. We stayed clear of alcohol and also had quite light meals. By the way if you like trying new things the alpaca meat was wonderful.

I'll leave it there. If you want to know anything else I'm happy to try to answer.

Cheers,
Steve

**Comment by Haacked** [comment]
@stevejgordon Thank you very much for the feedback! I really appreciate the write-up!

> I believe you can order them in advance and I do recommend it since they limit numbers each day.

Do you recall how or where you ordered them?

**Comment by stevejgordon** [comment]
@Haacked You're welcome. We got as our entrance tickets and ticket for Machu Picchu mountain as part of out trek with a well reviewed company called SAS Travel - http://www.sastravelperu.com/english/

I'm not sure if the sell only the entrance tickets but it might be worth checking. They are a little slow to respond to emails but were very reliable and helpful.
