### ISSUE TITLE
Advice for transitioning into Product/Program Management?

### ISSUE THREAD

**Issue by TheRealJZ** [Haacked/feedback#129]
Hi Phil!

Through 4 years of using C# MVC professionally, and more recently GitHub for Windows, I've really come to admire your driving force as a Product Manager. Thanks for continuing to set a high bar and ship products that make my life smoother every day!

For the past 7 seven years, drive and a passion for learning have carried me through building useful software on top of many different technologies. Lately, I'm most interested in the questions "what to build?" and "why build it?"  I've been delving into these questions on my most recent projects, which brings me to my ask:

Would you be so kind to suggest someone for me to talk to in order to land a role as Product/Program Manager at Microsoft or GitHub as my next position?  Any advice would be deeply appreciated!  

Thank you for taking time to read this, and for your contributions to the C# community!

Best Regards,
John Zumbrum

jzumbrum@outlook.com
http://johnzumbrum.com

**Comment by Haacked** [comment]
Hi John,

Thanks for the kind words. 

> Would you be so kind to suggest someone for me to talk to in order to land a role as Product/Program Manager at Microsoft or GitHub as my next position?

I know Microsoft is always hiring PMs. We have a few positions open too https://jobs.lever.co/github. Good luck!

**Comment by TheRealJZ** [comment]
Thanks Phil!  Will check it out!
