### ISSUE TITLE
Custome Github Extension in Visual Studio

### ISSUE THREAD

**Issue by chammua** [Haacked/feedback#130]
Hi Haacked!
Currently, i have a problem need your help. When i commit message to Github Extension in Visual Studio, i need get a little information as: username commit, commit message... for export this one to file excel.

How can i trigger event commit to Github in Visual Studio? If there have any solution solve this one, please help me.

Thank you so much!
TuanLV

**Comment by Haacked** [comment]
The GitHub Extension to Visual Studio doesn't handle commits. That's the Git extension built into Visual Studio. I don't think they support Git commit hooks. The best you can do is use the `git log` command from the command line with one of the `--pretty=format:...` options. https://git-scm.com/docs/git-log

**Comment by chammua** [comment]
I will try it and thank you so much!
Tuan

2016-02-19 6:14 GMT+07:00 Phil Haack <notifications@github.com>:

> The GitHub Extension to Visual Studio doesn't handle commits. That's the
> Git extension built into Visual Studio. I don't think they support Git
> commit hooks. The best you can do is use the git log command from the
> command line with one of the --pretty=format:... options.
> https://git-scm.com/docs/git-log
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Haacked/feedback/issues/130#issuecomment-185975409>.
>



-- 
Luu Van Tuan

Skype: chammua
Phone: +841248617647
