### ISSUE TITLE
<blockquote> doesn't display correctly when immediately following <h2>

### ISSUE THREAD

**Issue by schlueter** [Haacked/feedback#131]
At your archived article [the-eponymous-laws-of-software-development](http://haacked.com/archive/2007/07/17/the-eponymous-laws-of-software-development.aspx/) I noticed that the border of `blockquote` tags extends into `h2` tags immediately prior:
![Broken](https://github.bschlueter.com/images/linking/Haacked%20blockquote%20before%20h2%20Broken.png)

One solution to this is to add empty `p` tags between the two:

![Working](https://github.bschlueter.com/images/linking/Haacked%20blockquote%20before%20h2%20Working.png)

**Comment by Haacked** [comment]
Thanks for the report! I pushed a CSS change that should fix it when the site regenerates.
