### ISSUE TITLE
Haacked Nuget

### ISSUE THREAD

**Issue by mj-nowak** [Haacked/feedback#132]
Hey!  Sorry to bother you but I just had 2 quick questions I was hoping you could answer for me if you have the time.  We have been using your Haacked Nuget repo for the good part of the last year and it is built into a few of our centos images.  I went to update one of them and noticed your repo is no longer reachable, will you no longer be supporting this?  Also, I checked the last version we pulled from you and it is 2.8.5, where as if I pull down Nuget's actual repo (per the instructions on their site) and build it from scratch it turns out as 2.7.4, am I missing something here?  Thank you for your time and help in advance!
-Marshall

**Comment by Haacked** [comment]
Hi @mj-nowak I was mirroring the old NuGet on GitHub which I believe corresponds to https://github.com/NuGet/NuGet2

Did you build that?
