### ISSUE TITLE
MVC bug?

### ISSUE THREAD

**Issue by brunosaboia** [Haacked/feedback#136]
Dear Phil,

It seems that I found a bug in MVC.

If you have a `@model` such as:

 `Dictionary<string, Dictionary<string, Dictionary<int, Dictionary<int, Dictionary<int, int>>>>>`

(I know that this structure is bad, that is not the point, so don't be angry at me :smiley: )

Then Intellisense stops working for that view, and trying to access you give a compilation error, which I am attaching.

. If you wrap this weird data structure in a class, then you can access it normally. 

Thanks,

Bruno

![capture](https://cloud.githubusercontent.com/assets/1746033/15945113/c9354eca-2e5e-11e6-9402-0c3c11706e5b.PNG)

**Comment by haacked** [comment]
Hi @brunosaboia, I no longer work at Microsoft. The good news is that you can report bugs with  ASP.NET MVC on GitHub at https://github.com/aspnet/Mvc.
