### ISSUE TITLE
Hello. 

### ISSUE THREAD

**Issue by josebarodriguez** [Haacked/feedback#138]
Hello!

I read you article about routing ignore:
http://haacked.com/archive/2008/07/14/make-routing-ignore-requests-for-a-file-extension.aspx/
I did it but dont work
routes.IgnoreRoute("{_file}", new { file = @"(._/)?file.xml(/.*)?" });

Can you tell me why it dont is working?

sorry for my  english,

Thank!

**Comment by haacked** [comment]
Because `{file}` only matches one segment of the URL. Try 

`routes.IgnoreRoute("{*file}", new { file = @"(./)?file.xml(/.*)?" });`
