### ISSUE TITLE
Seattle Software Craftsmanship in 2017

### ISSUE THREAD

**Issue by bm2yogi** [Haacked/feedback#142]
Hi Phil,

I don't know if you recall, but we ran into each other at QConSF last year. I wanted to follow up on my invitation from then. Sorry for the delay.

As our 2016 meetup schedule comes to an end, we're looking to line up guests for our 2017 meetups and I'd like to extend you an invitation to come share your thoughts with our group.

The last couple of years have challenged us with changes in our leadership team and finding a consistent venue for our meetups. For 2017, we're teaming up with CDK Global who'll be hosting our meetups in their International District offices. Our partnership with CDK Global is a good fit because of their demonstrated dedication to Seattle's developer community.

Our purpose is to create an environment where all developers can learn, share and grow as software professionals. The software industry faces its share of challenges. We hope to meet those challenges by championing and mentoring in the knowledge and practices that lead to sustainable, quality software and healthy, productive teams.

We invite you to come share with our group because we believe that, in some way, we are both motivated by this common goal. You are well respected in the developer community and we'd like to give you another platform from which you can share your ideas on how together we can make things better.

Our primary meetups are on the fourth Thursday of each month from January through October, and we occasionally schedule special events on an ad hoc basis. 

Would you please consider this and contact me to discuss details?

Sincerely,

Michael Ibarra
Seattle Software Craftsmanship
www.seattlesoftwarecraftsmanship.org

**Comment by haacked** [comment]
@bm2yogi cool. I sent you a message via the Meetup site.
