### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jglasgow3** [Haacked/feedback#143]
Hi Phil,

I apologize for sending this directly to you, however, I want to make sure this gets to the right person and I know that you have been working at GitHub for a couple years now (based on listening to .net rocks).

I've recently started at Northampton Community College as a director, overseeing a group of developers (who have been using RCS for version control).  The group, is very eager to get off of RCS and onto Git.  I applied for an educational license for the group and I was surprised last night to see that we now have unlimited repositories and users!

Please share my sincere gratitude with whomever approved this, it was very unexpected and very much appreciated.

Sincerely,
John Glasgow

**Comment by haacked** [comment]
@jglasgow3 I think that would be the education team at GitHub https://education.github.com/. I shared your gratitude with them. Enjoy GitHub!
