### ISSUE TITLE
Writing a guide for Git under Windows

### ISSUE THREAD

**Issue by wsargent** [Haacked/feedback#145]
I've been working on a guide for people moving onto Windows from MacOS (following the MBP debacle):

https://gist.github.com/wsargent/072319c2100ac0aea4305d6f6eeacc08

Most things work, but I haven't been able to get GPG4Win very well integrated, or the Windows version of OpenSSH working with gpg-agent.  Do you know of any solutions or workarounds?

**Comment by haacked** [comment]
@wsargent I haven't attempted it yet. What specifically goes wrong with each?

**Comment by wsargent** [comment]
https://gist.github.com/wsargent/072319c2100ac0aea4305d6f6eeacc08#using-gpg-agent-instead-of-ssh-agent

It looks like setting SSH_AUTH_SOCK to gpg4win does not make ssh happy:

```
set SSH_AUTH_SOCK="C:\Users\wsargent\AppData\Roaming\gnupg\S.gpg-agent.ssh"
```

Then you get:

```
D:\work\docker-cheat-sheet>ssh-add
Could not open a connection to your authentication agent.
``

**Comment by haacked** [comment]
I'm not sure. I mentioned it to my co-worker @shiftkey who may spend some time looking into it. But I can't promise a resolution any time soon.

**Comment by haacked** [comment]
If this is still an issue, please email support@github.com. Thanks!
