### ISSUE TITLE
Blog inquiry

### ISSUE THREAD

**Issue by zeenadhalla** [Haacked/feedback#147]
Hi Phil!  Didn't find an email address for you... so here I go using Github for the first time.  Yes I am rather clueless in this arena.  Which begs the question... why am I contacting you!?

I am impressed with your site and would love to have a chance to write a guest post for your blog.  I see you're a super busy consultant and speaker, so having new content done for you might be a nice relief.  I notice you often write "lifestyle" pieces on your blog so you might be open to an idea that is outside the box.

I am a Certified Posture Specialist and I help technology professional eliminate neck and back pain as a results for sitting for too many hours a day in poor posture.  I have some blog post ideas for you if you're interested, but would prefer to pitch in a more "private" forum.  

My blog is: www.VerticAlign.com.  You can contact me there or send me your email address here.

And please forgive me if this is the incorrect forum to contact you.  I had a bit of fun exploring this site and figured it was worth a shot...

In health and good posture,

Zeena Dhalla

**Comment by haacked** [comment]
Thanks for the offer, but I prefer my blog to represent my thoughts. I have no interest in a guest blogger.

**Comment by zeenadhalla** [comment]
Makes total sense.  Thanks for the reply!!
