### ISSUE TITLE
can you show how to use asp.net mvc as plugin based system

### ISSUE THREAD

**Issue by aloksharma1** [Haacked/feedback#149]
basically what i want is to have a core asp.net mvc site serving as master and mini mvc sites as plugins which we can simply turn off/on by putting in dlls or removing them, i have been reading through all diff. mvc plugin frameworks but non seems to provide easy ways and some are dead links as of today :( , so i was hoping if you can point me in right direction.

thanks

**Comment by haacked** [comment]
I don't have a good resource for answering this question. Sorry.
