### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by pshelton-skype** [Haacked/feedback#150]
The SSL certificate for https://haacked.com was issued by GitHub and covers only GitHub-related domains:

DNS Name=*.github.com
DNS Name=github.com
DNS Name=*.github.io
 
Users will receive a NET::ERR_CERT_COMMON_NAME_INVALID error in browsers when following HTTPS links to the website.

**Comment by haacked** [comment]
Fixed.
