### ISSUE TITLE
.NET DeveloperDays invitation

### ISSUE THREAD

**Issue by mpilecki** [Haacked/feedback#153]
Hi Phil,
I am trying to reach out to you in order to invite you to our .NET development conference taking place in Warsaw in October. I hope this is a good chanel, as I was unable to locate your email address anywhere.

Our conference is large (we had 900 people last year and expect 1000 this year) and international (23 countries represented last year). It's a well-organized event and I think you would enjoy presenting there.
We are looking for a star speaker to deliver a compelling keynote and your session on the future of programming would be a perfect candidate.
We do pay all speaker T&E and may pay a small speaker stipend if necessary.
You can check our website at: http://net.developerdays.pl/

I hope you will accept our invitation and look forward to welcoming you in Warsaw.

Please get back to me at maciej@data-master.pl and let's talk.

Thanks and best regards,
Maciej

**Comment by haacked** [comment]
Hi @mpilecki thanks for the invite. Sorry for the late response, but I won't be able to make this. I really appreciate you thinking of me though.

**Comment by mpilecki** [comment]
Hi,
Sure, no probs. Interested in discussing 2018?

M.

2017-09-24 18:30 GMT+02:00 Phil Haack <notifications@github.com>:

**Comment by haacked** [comment]
Feel free to email me at haacked@gmail.com. It's probably too early to make 2018 plans, but I'm open to hearing details. 😄
