### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by IanFelton** [Haacked/feedback#157]
Hi Phil,

I feel a little weird leaving this message here, but I linked through your blog, so what the hell.

My name is Ian Felton. I recently published a scifi IT book. I wanted to honor your contributions to my software development career by sending you a copy (or a Kindle version).

It’s called “The Coding Samurai.” Please let me know where I can send it.

This is the link to the book on Amazon.
https://www.amazon.com/Coding-Samurai-Way-Computer-Warrior/dp/0998690902/

Sincerely,
Ian Felton

**Comment by haacked** [comment]
Ha! Nice! Email me at haacked@gmail.com
