### ISSUE TITLE
Develop a Video Tutorial on C# 7 and .NET Core

### ISSUE THREAD

**Issue by KevinSequeira** [Haacked/feedback#158]
Hi Phil,

My name is Kevin. I'm an Acquisition Editor with Packt.
 
We're planning on developing a video tutorial on C# 7 and .NET Core Projects, and are looking for professionals who'd like to join us as Authors. You've been senior program manager at Microsoft's ASP.NET Team. You're also an active blogger on your personal website, and have been named among the top .NET developers to follow by NewRelic.com.
 
I believe you'll make a fine Author for this course, and would love to have you over this video tutorial as Author.
 
Let me know if you're interested, and I'll share more details on the project.

Thanks,
Kevin Sequeira
iamkevinsequeira.com
Video Acqusition Editor, Packt

**Comment by haacked** [comment]
Hi @KevinSequeira, sorry for the late reply. I took a leave from work and all things tech. I'm back, but really busy. I like the idea of this series, but I don't have the bandwidth to do it.
