### ISSUE TITLE
GitHub for Designers

### ISSUE THREAD

**Issue by argyleink** [Haacked/feedback#161]
Hi Phil! ☺️🖖

I went looking for the team behind GitHub for Mac/windows today because I wanted to check in to see if they were hacking on a version for designers. Found you via Google searches, got pumped you were in the area.

GitHub has won the hearts of developers through superb open source tooling, reliable services, etc. GitHub is an extremely respectable company to me and the others in my community. I'm hoping there is a secret project there that's trying to tackle design versioning. It's not a new idea, currently Kactus, Folio and Abstract are battling for adoption, and I believe firmly that GitHub needs to have a stake in this game. Git LFS felt like a step towards enabling such tools, but it's been a couple years and I don't see any scents of a GitHub for Designers workflow. 

So I'm pinging you because I want to implore you or GitHub to get in this design versioning game, and win it like you have with Atom and GitHub for Desktop! If there is no team or project brewing, I want to join and help lead it. I'm confident that I could product lead the tool to success, especially in an environment that desires quality. I could talk more about my background to qualify myself, if this sounds interesting.

Sorry to ping directly! Sort of out of the blue, but I've been testing design versioning systems for a while now, pushing our design team to optimize their workflow. I believe that design versioning will be the next design process workflow game changer. The tool to first make it easy enough for the cautious design community, is going to profit. No one is better positioned to win those hearts than GitHub.

Hope this finds you well, I wrote it on the bus because I needed to get this off my chest to an ear I think it could resonate. I'd love to hear your opinions on the topic, I doubt that GitHub considering a design versioning product is new, at least I hope not. 

Take it easy! Excellent job on GitHub for Mac, I use it for 90% of my git workflow. 

🤘
Adam Argyle
argyleink (GitHub, Twitter)

**Comment by haacked** [comment]
Hi @argyleink! Appreciate the note. I'm not aware of any plans, but if I were, and they were secret, then I would be obliged not to say anything. 😛

What I will do is pass this along to folks who might be more clued in to any such efforts should they exist.

**Comment by argyleink** [comment]
🖖
