### ISSUE TITLE
No Issue:  A question rather 

### ISSUE THREAD

**Issue by pawna** [Haacked/feedback#162]
Hello there,

I have just started to work with Asp.Net and came across your blogs.  Very helpful, and congratulations on the promotion.  

One thing that is missing is, I am unable to search on your site for specific nfo for  Razor or ASP.NET 

Would you happen to have a blog for Razor if statement by any chance? 

Thank you in advance for your help and time!

**Comment by haacked** [comment]
@pawna something like this? http://haacked.com/archive/2011/01/06/razor-syntax-quick-reference.aspx/

**Comment by pawna** [comment]
Thank You Phil!
