### ISSUE TITLE
Invitation to Speak at CodeCampSDQ:Evolved - December 2nd

### ISSUE THREAD

**Issue by hminaya** [Haacked/feedback#163]
Hi!...

I’m the technical lead for CodeCampSDQ, we are a community driven conference that takes place every year in December in the Dominican Republic (https://goo.gl/maps/5wGe5hQ6pDv). We believe in diversity which is why we always have a broad range of international and local speakers.
 
The reason I’m reaching out to you is that we’d like to invite you to speak at our event, it would be a great honor for us all. A lot of us have followed your career throughout your tenure at Microsoft back in the early asp.net mvc/c# days and now at github.
 
Please let us know if you’d be interested so we can talk about logistics, if you have any questions please feel free to reach out to me for more information. Also, you can find out more about us @
 
- http://codecampsdq.com/
- https://www.facebook.com/CodeCampSDQ/?ref=br_rs

**Comment by haacked** [comment]
I responded via email. Thanks!
