### ISSUE TITLE
MVC URL Parameter Question

### ISSUE THREAD

**Issue by jigarce** [Haacked/feedback#165]
HI,

I have url  as below 

http://localhost:50143/adminpanel/category/categorylist/4

Now i would like to use Querystring paramter 4 in another @Url.action paramter.

Tried google not working.

i got below  answer but its now working
In view i have written below code, i need value 4 in anchor tag HREF
href='@Url.Action("products","product",new { ID= UrlParameter.Optional} )'

How do i get ID value in VIEW ,

Regards,
Jigar

**Comment by haacked** [comment]
> Now i would like to use Querystring paramter 4 in another @Url.action paramter

What QueryString parameter? I don't see any query string in the URL example you posted.
