### ISSUE TITLE
I am interested in examples of using git in Government for NON software app

### ISSUE THREAD

**Issue by SteveStrongApp** [Haacked/feedback#167]
Phil,

I think I remember you discussing other uses of git hub,  for example tracking changes in writing laws.  

Can you point me toward examples and case studies?

**Comment by haacked** [comment]
Hi @SteveStrongBAH, I think https://government.github.com/ has links to the resources you need. For example, https://government.github.com/community/.

Some of the laws on GitHub are being done unofficially. For example, the German Federal Laws are on GitHub: https://www.wired.com/2012/08/bundestag/
