### ISSUE TITLE
How to add line items on the same view in mvc 5 i.e order along with line items

### ISSUE THREAD

**Issue by Mujtaba1995** [Haacked/feedback#168]
Hello!!

currently, I'm working on my order module and I want to post order along with its line items in mvc5  could you please provide me its source code or complete explanation I will be very thankful to you   

Thanks

M.Mujtaba Khan

**Comment by haacked** [comment]
This might be a better question for StackOverflow. I recommend asking a more detailed question though. What have you tried. What's not working? Etc.
