### ISSUE TITLE
Interested in open source for science?

### ISSUE THREAD

**Issue by CBenghi** [Haacked/feedback#169]
Hello @Haacked,

Perhaps you are familiar with the work of http://joss.theoj.org/, which is an developer friendly peer-reviewed journal that publishes quality software packages that can support scientific research. All of their work is done in the open on Github (https://github.com/openjournals/joss-reviews).

I've submitted a contribution that is based on .Net, but they don't have any editors familiar with the technology and asked me to suggest one (https://github.com/openjournals/joss-reviews/issues/395). 
I've volunteered to edit future .Net submissions, but obviously can't review my own.

After listening to you on DotNetRocks, I thought you might be interested in helping.
The review process is quite straightforward.

Please, let me know.

Best regards,
Claudio

**Comment by haacked** [comment]
What would I need to do?

**Comment by CBenghi** [comment]
Thanks for getting back.
The journal provides [instructions on the review process](http://joss.theoj.org/about#submission_requirements). They are fairly simple, I think.

I've gone through the list and I hope that the submission matches all the expectations, but if you find it lacking I'll be very keen to rectify the work on your feedback.

If you are happy to support this, the next step would be jump in on [the thread of the Joss-Review](https://github.com/openjournals/joss-reviews/issues/395) and ask Arfon (the editor in chief) to make you the editor of the submission. 

Claudio

**Comment by CBenghi** [comment]
Hi @Haacked,
just a gentle reminder to see if you are interested.
Thanks,
Claudio

**Comment by haacked** [comment]
@CBenghi FYI, I ran the unit tests and one fails in master right now. `CanParseNewlinesInStrings`

**Comment by CBenghi** [comment]
Many thanks @Haacked,
Your help is very much appreciated.
I've fixed the failing test and merged your PR on the license.
I'm looking forward to Arfon's response.
