### ISSUE TITLE
publishing a review

### ISSUE THREAD

**Issue by callpri** [Haacked/feedback#170]
Hi.
 
We would like to  publish  a review about our free PHP IDE - Codelobster PHP Edition
http://www.codelobster.com 
It has also plug-ins for  Magento, Laravel, CakePHP, Phalcon, Joomla,  Drupal, Wordpress, Symfony, Yii development and many other PHP frameworks.
 
It can be guest post or your own opinion.
  
How we can do it? 

PAD URL is:
http://www.codelobster.com/download/clphped.xml 
  
Thanks.
Stas Ustimenko.
Codelobster Software.

**Comment by haacked** [comment]
Create a blog and publish it there.
