### ISSUE TITLE
Phil Haack - 

### ISSUE THREAD

**Issue by CanYouProgram** [Haacked/feedback#173]
Hello,

I don't know if this is the best way to get to contact you but I am trying to teach myself MVC.I am new to ASP.NET and I have listened to two of your podcasts, from when MVC was still called NuPack. I am looking for more info on this. There surely must be more content to be read through. It's making me feel as if maybe its not going to be as popular and that I should teach my self another stack.

Thanks,

**Comment by haacked** [comment]
Sorry I missed this question. Not sure why I didn't get the notification. Hope you were able to answer your question.
