### ISSUE TITLE
Thanks for the Blog!

### ISSUE THREAD

**Issue by cclambie** [Haacked/feedback#174]
Hi Phil,
Thanks for the blog, it was really handy today when I was hunting for a way to pull an SVN repo into GitHub (my favoured repo client)

This is a regular thing, I read so much amazing content on the web, and I don't support it all, so I came up with a Netflix like subscription service that allows creators like you to get paid, and consumers like me to make sure you get paid, without clicking on an ad.

So... given this, I am seeing if this is of interest to you, maybe your experimental mindset will take you to experiment with this?
I call it Micropayz dot com.

Love to know your thoughts, there is a little explainer vid on the website, and that is all at the moment, adding some FAQs as I come up with them.
I am thinking of ways to integrate into Open source software usage - like Wordpress Plugins or Themes... or just snippets of code on GitHub....

Cheers

Craig Lambie
All contact info at 
craiglambie dot com

**Comment by haacked** [comment]
@cclambie thanks for the kind words. Not sure why I didn't see this until now. :cry: I tried the site but looks like I missed the boat. :smile:

**Comment by cclambie** [comment]
Yes sorry I shut site down.
Now Flattr essentially does the job, especially for a blog like yours, worth signing up if you haven't already, spread some love 👍 
Cheers
