### ISSUE TITLE
GitHub in Alaska

### ISSUE THREAD

**Issue by carterbancroft** [Haacked/feedback#175]
Hi Phil,

A few years back I attended a small talk you gave in Anchorage on your work at GitHub. I really enjoyed it, thanks again for that. I recently applied for a position at GitHub as an engineer on the Atom team and was disappointed to learn that GitHub can't hire remotely in AK.

I know it's a long shot and perhaps you aren't the best person to reach out to about this but you came to mind immediately being a fellow Alaskan inside of GitHub. I'm just hoping to figure out what it would take, if anything, to open up hiring in our great state.

I'm trying to keep this short and to the point and I'm sure you're very busy so I completely understand if you don't have time or don't know what the answer is. But, if you'd like to learn more about me my LinkedIn is here [here](https://www.linkedin.com/in/carter-bancroft-a6b6056) and I have an about.me page [here](https://about.me/carterbancroft). My email address is carter.bancroft[at]gmail.com.

Thanks again. I always enjoy the blog.

Take care,
Carter

**Comment by haacked** [comment]
Hi @alt234, thank you for your interest in GitHub!

Presently, we can employ individuals in the following 19 countries: Australia, Austria, Canada, Denmark, France, Germany, Ireland, Japan, Netherlands, New Zealand, Scotland, Spain, Sweden, Switzerland, the United Kingdom (England, Northern Ireland, Scotland, and Wales), and the United States (only 33 states).

Here is the complete list: https://github.com/about/careers/remote

>  I'm just hoping to figure out what it would take, if anything, to open up hiring in our great state.

Yeah, sorry I can't be very specific about this. A variety of factors affect whether we go through the cost and effort to add new cities to the list. I suppose one thing you can do is help build a strong tech community in Alaska to get our attention. I no longer live there, nor do I have family there, but it is near and dear to my heart still. I'd be happy to come speak again someday.

If your location changes, I encourage you to take another look at our GitHub Career's Page for future opportunities. I wish you the best of luck in your search!

**Comment by carterbancroft** [comment]
No worries. Thanks so much for the response! Would love to catch another talk someday.
