### ISSUE TITLE
Ownership of OpenSource

### ISSUE THREAD

**Issue by ghost** [Haacked/feedback#176]
I have a friend who might be dealing with some serious charges for accessing OpenSource software that he installed on his web server. Possibly a "Founders Copyright" might apply.   The control of that web server account was taken from him and then he was terminated.   Who owns the OpenSource software now?  Who can rightfully access the code?  The webserver account that was taken contol of wapart of his wholy owned LLC

**Comment by haacked** [comment]
Not sure why I didn't notice this question before, but a situation like this is best left to a lawyer. I wouldn't feel comfortable giving legal advice.
