### ISSUE TITLE
malicious links in blog comments

### ISSUE THREAD

**Issue by mpictor** [Haacked/feedback#177]
If you look at the comments on https://haacked.com/archive/2004/11/18/church-signs.aspx/ , there's one from `Homeless Guy` with links that _appear_ to go to sparemesomechange.com. However, when I clicked the first I was sent to http://disq.us/url?url=%3Ca+rel%3D%3AzsrKA9z4qk6gWrNSMIS05yBLoJY&cuid=2103057 . According to my history that sent me through a few more redirects
https://sarah.runtnc.net/tr?id=01624900059f846986449f0c9c738d40f58806ee49.r&tk=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWIiOiI1MjJjNjE1YTlhODQ4MGNhYjhiMTA0MTIiLCJ0cyI6IjAxMTcyMzQyIiwiZCI6InM2MGJsb2cuY29tIn0.0-RWyJ78pTkgdWciDatLoj7tQ641MNO1HY0xdbyFgl8#comment-9005499
and http://secure.calcch.com/performance/bdv_rd.dbm?enparms2=5140,1905692,2593116,5091,5099,14090,5301,0,0,5095,0,1907336,545062,239312,18448004549,154207654,nlx.ux3x143131397x27vwyvvx45&ioa=0&ncm=1&bd_ref_v=www.bidvertiser.com&TREF=1&WIN_NAME=&Category=1000&ownid=54ceebde72c793131341c3cf&u_agnt=&skter=tloy06h%2Btloy&skwdb=ooz_wvvu
which then sent me to http://missingcrack.tk/ which informs me that my computer is infected. Unfortunately for them, I'd probably have no more luck running their "fix" than the [`A Lower Total Cost of 0wnership`](https://www.immunitysec.com/downloads/tc0.pdf) author had 😉

**Comment by haacked** [comment]
Thanks! I marked it as spam and removed it.
