### ISSUE TITLE
Careful now: possible recursion detected

### ISSUE THREAD

**Issue by bartelink** [Haacked/feedback#179]
In https://haacked.com/archive/2018/01/27/analyze-github-issue-comment-sentiment/ you have requested that I:

>`Install-Package nuget`

I'm scared this might cause a DDOS attack.

Maybe using `octokit.net` might serve to mitigate?

Please refer to [this issue](https://github.com/Haacked/feedback/issues/179) for further details.

Also, in same post, should linkify https://github.com/haacked-demos/azure-sentiment-analysis/

**Comment by haacked** [comment]
Ha! Whoops. Thanks! I fixed it.

**Comment by bartelink** [comment]
Looks better ;) (But the github link is still text)

And thanks for doing the demo and the post!

**Comment by haacked** [comment]
Which link? Also, you can click the edit link in my posts if you want to
propose a fix and get credit. :)

**Comment by bartelink** [comment]
Wait, the edit link is news/not prominent enough for me, will do! No credit needed (I had a quick scan for a blog repo but didnt find one!)

**Comment by haacked** [comment]
> no credit needed

I can't help it. My "contributors" page is built off of GitHub data. So if you submit a PR with a proposed correction and I merge it, you automatically show up on this URL: https://haacked.com/contributors/

**Comment by bartelink** [comment]
Nice. One tile won't repave my shower mosaic alone but hey...

Re the edit link, I didnt see the haacked.com repo pinned in github.com/haack so gave up.

The edit link at the top of the page does not jump out as a "anyone could click this" to me, even if, now that I know what it is, it seems perfectly reasonable and friendly (in my head as I scanned it I reckon it got lumped, unfairly, in the "artifact of blog engines that expose admin links as part of the text with undue prominence" bucket).

**Comment by bartelink** [comment]
🤔 Perhaps cloning Edit pencil as a [suggest and edit for this page] long-titled link at the bottom of the page might better align with where/when people will expect to find such a link ?

**Comment by haacked** [comment]
@bartelink interesting idea. So make it more clear that you can suggest an edit?
