### ISSUE TITLE
Make the ability to suggest edits more prominent

### ISSUE THREAD

**Issue by haacked** [Haacked/feedback#180]
See #179 for a discussion of this. Perhaps something at the bottom of the blog post.

**Comment by haacked** [comment]
Some more context...

> The edit link at the top of the page does not jump out as a "anyone could click this" to me, even if, now that I know what it is, it seems perfectly reasonable and friendly (in my head as I scanned it I reckon it got lumped, unfairly, in the "artifact of blog engines that expose admin links as part of the text with undue prominence" bucket).

**Comment by bartelink** [comment]
FYI My suggestion was inspired by @ploeh's impl on his blog, e.g. see footer of http://blog.ploeh.dk/2018/01/29/argument-list-isomorphisms/
