### ISSUE TITLE
Copyright Question

### ISSUE THREAD

**Issue by smorgan2018** [Haacked/feedback#185]
Hi,
I read Part 1, 2, and 3 of your articles on copyrighting software.  I modified portions of code on an action wizard (javascripts) offered for free by Adobe at https://www.pdfscripting.com/public/main.cfm.  I modified it enough for it to fall under the definition of a derivative.  I looked at the legal statements at  https://www.adobe.com/legal/terms.html and it appears that all of their works are copyrighted and under section 5 called "User Conduct," it cannot be modified.  However, I am still unclear if I can copyright my portion of the modified code as a derivative per section 3 "Your Content" section.  The two sections seem to conflict.  Maybe you can help me sort this out?  I would like to copyright as a derivative ASAP if I am allowed to.  Thanks in advance.

**Comment by haacked** [comment]
Sorry I missed this question when you asked it originally. This question is best left to a copyright laywer.

**Comment by smorgan2018** [comment]
Can u recommend one?

**Comment by haacked** [comment]
I don't know of one off the top of my head. I've heard of folks who had good results with https://www.upwork.com/ or https://legalzoom.com.

**Comment by smorgan2018** [comment]
I really appreciate your response. Thx. :)
