### ISSUE TITLE
Subtext

### ISSUE THREAD

**Issue by Rodbourn** [Haacked/feedback#187]
First, thank you for a blog engine that has held up for over a **decade**.  I was curious if you ever provided a migration path for Subtext to another project?  My blog has been up since may of '08 and I'd like to retain as much as I can.

**Comment by haacked** [comment]
Hi @Rodbourn! Sorry for the very late response.

I did write some scripts to export Subtext for use with Jekyll.

* https://github.com/Haacked/subtext-jekyll-exporter

They're very rough though.

**Comment by Rodbourn** [comment]
Thank you!
