### ISSUE TITLE
Acquisition?

### ISSUE THREAD

**Issue by rmegal** [Haacked/feedback#188]
Mr Haack,

I have been following your blog for some time now and would very much like to hear your thoughts on the acquisition of GitHub by Microsoft since you're in the unique position of leaving MS for GitHub. As someone who has gone through acquisitions I realize this may be too personal to share publicly, so feel free to ignore this. I mean this only as an encouragement if you're thinking about posting on this topic.

Thanks,

Ray

**Comment by haacked** [comment]
Hi @rmegal! I probably won't post on the subject, but I did do an interview with .NET Rocks where we talked about this a bit. https://www.dotnetrocks.com/?show=1553
