### ISSUE TITLE
Google Partner - suggestion for haacked.com

### ISSUE THREAD

**Issue by hstoever** [Haacked/feedback#196]
Hi  Phil,

I'm very impressed with the work you've done on haacked.com! Your passion for web development and your dedication to sharing your expertise with other aspiring software engineers is quite admirable! I also noticed that you're from Bellevue - I grew up in Bellingham but have family in Bellvue, it's a beautiful place to live.

I'm reaching out to ask if you've ever considered using ads on your site?

I work at Ezoic (a Google Certified Publishing Partner), and I'd love to chat with you about how our platform allows you to generate incremental income with 0 risk and no maintenance. 

Ezoic uses AI to curate the exact Ad compositions (size, color, location, etc.) that resonate best with each unique visitor. 

Is testing ads something you've done before? 

Regards,

Hannah
Business Development Manager, Ezoic
hstoever@ezoic.com

**Comment by haacked** [comment]
I already have ads on my site. Thanks.
