### ISSUE TITLE
TRS-80 16 or 32KB?

### ISSUE THREAD

**Issue by alfredorevilla** [Haacked/feedback#197]
Which one was yours? Honestly I don't remember which one I had but I guess it was the 16 KB model but it was super fun. Oh and when the tape recorder arrived I was in heaven, I could actually save my code!!! 😲

**Comment by alfredorevilla** [comment]
Which one was yours? Honestly I don't remember which one I had but I guess it was the 16 KB model but it was super fun. Oh and when the tape recorder arrived I was in heaven, I could actually save my code!!! 😲

**Comment by haacked** [comment]
I don't remember, but I assume it was 16kb.
