### ISSUE TITLE
Publish a book with Packt Expert Network

### ISSUE THREAD

**Issue by DavidBarnes** [Haacked/feedback#200]
Hi Phil,

I'm a book producer at Packt Expert Network. We're inviting established tech authors to work with us, and putting together an author benefits package that works better for expert authors than other publishers.

If you're open to writing another book in the future, I'd very much like to talk to you about what we could offer you.

Email me on davidb@packt.com and I'll follow up with more details.

David

**Comment by haacked** [comment]
I replied via email.
