### ISSUE TITLE
Podcast invite

### ISSUE THREAD

**Issue by ovation22** [Haacked/feedback#201]
Hi Phil,

Congrats on the .NET Foundation Board position!

Would you be interested in coming on The 6 Figure Developer Podcast (https://6figuredev.com/category/podcast/)? I had reached out shortly after the GitHub acquisition was announced and you were understandably busy. Would you have availability in late May? We would still love to have you on.

Please let me know if you have any questions.

Thank you,
John F. Callaway, Jr.

**Comment by haacked** [comment]
Sure! Feel free to email me at haacked@gmail.com
