### ISSUE TITLE
Remove your CNAME or take it back

### ISSUE THREAD

**Issue by tampanraja** [Haacked/feedback#202]
Hi there,
I think this blog is very important for you.
I just got vulnerabilitiy subdomain takeover from one of your sub domain.
here's the sub domain :

> [https://stage.haacked.com/](https://stage.haacked.com/)

you can reply this comment to take the subdomain or just remove the CNAME.
Keep it safe.

**Comment by Haacked** [comment]
Thanks for the heads up. I removed the CNAME.
