### ISSUE TITLE
Internal broken links

### ISSUE THREAD

**Issue by chrisofspades** [Haacked/feedback#203]
It looks like many of your older posts have internal links that are broken. For example, in this post:

https://haacked.com/archive/2005/11/02/dynamic-vs-inline-sql.aspx/

There is a link for https://haacked.com/archive/2005/11/01/WhereTheProviderModelFallsShort.aspx

That link is broken. Here is the actual link for that post - https://haacked.com/archive/2005/11/01/wheretheprovidermodelfallsshort.aspx/

So it seems the culprit here is case sensitivity.

**Comment by haacked** [comment]
Thanks for the report! I fixed it. It may take a few minutes for the site to update.
