### ISSUE TITLE
Missing articles

### ISSUE THREAD

**Issue by purplepangolin** [Haacked/feedback#204]
Hi,

Not sure what is happening with your blog, but I have seen quite a few articles appear in my feed reader recently which give a 404 if I try to follow the link to the actual blog post. e.g. https://haacked.com/archive/2019/04/19/2005-11-02-dynamic-vs-inline-sql.aspx/
https://haacked.com/archive/2019/04/19/2005-07-14-google-has-the-answer.aspx/
https://haacked.com/archive/2019/04/19/2004-12-06-unit-testing-benefits.aspx/
etc.

The most recent link that appears to work is https://haacked.com/archive/2019/04/03/nuget-package-signing/

**Comment by haacked** [comment]
Yeah, I was doing some cleanup and made a few mistakes which caused the wrong URLs to appear in the RSS feed for a short period of time. The posts that 404 are old posts. Here are the correct URLs.

https://haacked.com/archive/2005/11/02/dynamic-vs-inline-sql.aspx/
https://haacked.com/archive/2005/07/14/google-has-the-answer.aspx/
https://haacked.com/archive/2004/12/06/unit-testing-benefits.aspx/
