### ISSUE TITLE
Nefarious Link

### ISSUE THREAD

**Issue by d-dubz** [Haacked/feedback#205]
On page...

https://haacked.com/archive/2011/10/04/prevent-forms-authentication-login-page-redirect-when-you-donrsquot-want.aspx/

The link was in the beginning of the "Register an HttpModule to convert Redirects to 401" section and was titled "This blog post". The url of the link is

http://amilagm.com/2010/11/prevent-forms-auth-from-redirecting-to-login-page-in-restful-wcf/

... it looks ok but doesn't point to to the article but to an adult site with loads of pop ups.

**Comment by haacked** [comment]
Thanks for the report! I published a fix that should be up soon.
