### ISSUE TITLE
Interesting Feedback Mechanism

### ISSUE THREAD

**Issue by billyzkid** [Haacked/feedback#212]
Hi Phil! Your name just popped into my head so I stopped by to say hi. Lots of interesting, important work you've done over the years. There's not many of us representing Oxy in CS I fear. After 15 years at Vertigo, I'm currently working at Disney now on Disney+ (Xbox) so that's sorta cool.

-Will

**Comment by haacked** [comment]
Oh nice! That's quite the move!
