### ISSUE TITLE
Question about your experience with RDP

### ISSUE THREAD

**Issue by johnvondoe** [Haacked/feedback#216]
Hi,

I recently stumbled upon your post, and found it very interesting. 
https://haacked.com/archive/2010/05/18/remote-desktop-file-copy.aspx/

And my question is - by "drag and drop" did you, by any chance, mean dragging a file from the Remote Desktop window and dropping it outside of that window to your local system?
 .____________________________________________
|⠀⠀____________⠀⠀⠀⠀ ⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀|
|⠀ I RDP_____ x I⠀⠀⠀ ⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀|
|⠀ I⠀⠀⠀⠀⠀⠀⠀⠀I⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀|
|⠀ I ⠀ ⠀  ⠀📄---I--------- ▷ 📄 ⠀⠀⠀⠀⠀⠀⠀⠀ |
|⠀ I____________I⠀⠀⠀⠀ ⠀ ⠀⠀ ⠀⠀👆⠀⠀⠀⠀⠀⠀⠀|
|⠀ I⊞__________I ⠀ ⠀ ⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀|
|⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀|
|⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀|
|⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀|
|____________________________________________|
| ⊞ |⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ |
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

I hoped you might remember this, because you actually documented the feature.

Cheers.

**Comment by haacked** [comment]
> mean dragging a file from the Remote Desktop window and dropping it outside of that window to your local system?

Yes. That's exactly what I mean. And it worked.
