### ISSUE TITLE
public use of your code of NamedStringFormatting solution?

### ISSUE THREAD

**Issue by russaa** [Haacked/feedback#222]
Hi,

I stumbled on your relatively old blog post about named-string-formatting, and have a question about it  
http://haacked.com/archive/2009/01/04/fun-with-named-formats-string-parsing-and-edge-cases.aspx/

My question:  
Would it be possible to use this code in a public GitHub project with a permissive license like the MIT license (or maybe you already have a LICENSE file that could be used for that purpose)?

I would be very interested in using & extending it with some custom options:
I did port it to .NET Core 3.1 and extended it a little bit for a private project, but I would like to put it publically on GitHub.

As you noted in an update of the blog posting:  
I think, string interpolation does not make this implementation irrelevant -- while it is great in some regards, it also has some limitations, e.g. that _alignment expressions_ must be `constant` which prevents some interesting use cases (e.g. that a user provides a custom formatting string with alignment in a GUI).

**Comment by haacked** [comment]
Sure! Check out the license section of my about page: https://haacked.com/about/

It states all code samples on my blog may be licensed under MIT.
