### ISSUE TITLE
Does your house still run on GitHub?

### ISSUE THREAD

**Issue by LizzySoltis** [Haacked/feedback#228]
Hello Xubber!  Current Hubber here working on a "Run your house on GitHub" side project & happened upon an old blog post of yours.  Would love to hear if you still use any GH tooling and any other takeaways.  I'm a TPM with small kids and an EM partner, so looking to monopolize on workflow, language, and tooling we work on all day and create a template that is shareable.  Cheers!

https://haacked.com/archive/2014/06/30/github-issues-saved-my-marriage/

**Comment by haacked** [comment]
:wave: We stopped a long time ago. While I loved it, the rest of my family just weren't interested. However, this was before Project Boards, automations, and when my kids were really young.

It's something I may consider again, but it's unlikely to take off unless I get one of those touch "appliance" computers where we could have the project board always up in the kitchen or something. 😆  My kids just don't check their emails or a website regularly. It'd have to have a "physical" and prominent presence in our home for it to work.
