### ISSUE TITLE
Asp.Net Route Twice

### ISSUE THREAD

**Issue by aminsoroush** [Haacked/feedback#28]
i have one address:
          http://www.example.com/search/cat1/cat2/Brand32
i want to first route to
          http://www.example.com/Search/cat2/#/cat1/cat1/Brand32
then route to aspx file like "List.aspx".

how to do? because i want to know cat2 value and then search in database bye cat2 value.when user visit page, in this example, see all products which has Brand32 condition in cat2 category . when user uncheck checkbox of Brand32 , user see all Products of Cat2 Category . i want to first route to virtual path then route to physical path .

**Comment by Haacked** [comment]
I recommend asking this question on StackOverflow and posting the link to this issue.
