### ISSUE TITLE
Hey !!

### ISSUE THREAD

**Issue by kanwar00733** [Haacked/feedback#31]
I am Kanwar from IIT PATNA (INDIA), I was going through your article on CSRF. I am doing my research in this particular topic. I am planning to make a browser plugin for CSRF protection based on injection of javascript code in the page itself. I am an amateur, can you please help me in any way? 
Anticipating your prompt reply.

Regards,
Kanwar

**Comment by Haacked** [comment]
Hi Kanwar, Did you have a specific question in mind?
