### ISSUE TITLE
Scheduled and Recurring Tasks in ASP.NET

### ISSUE THREAD

**Issue by BrianMullin** [Haacked/feedback#48]
Hi Phil,

Since you had some interest in WebBackgrounder in the past, I wanted to let you about a new open-source effort we are working on called, **Revalee**.

   GitHub repository: https://github.com/SageAnalytic/Revalee
   Project site: http://revalee.sageanalytic.com/

The aim is to schedule one-time and recurring tasks for ASP.NET applications without having to engineer a custom solution. As you know, application shutdown is a major obstacle for background tasks. Problems arise both due to sudden termination (solved by WebBackgrounder) and missing events while the application is not running.

Revalee is callback service that can trigger an ASP.NET application startup by issuing a HTTP request at the scheduled time. I conceptualize a Revalee callback as a long-term deferred promise. It allows you to design interactions that have a temporal delay embedded in the workflow. More of your processes can remain transaction oriented with time-based events without falling back to longer-running batch processing.

There are some examples of typical usage on the Revalee project site. We are trying to create something broadly useful for the .NET community and would love if you checked it out.

Thanks,
Brian
Twitter: @brmullin

**Comment by Haacked** [comment]
Hi Brian! Sounds cool! In all honesty, I probably won't have time to check it out. I sadly don't do a lot of ASP.NET development these days. I do a lot of WPF work believe it or not. :smile:
