### ISSUE TITLE
RouteMagic Handler

### ISSUE THREAD

**Issue by leon-andria** [Haacked/feedback#49]
It seems that the current implementation is related on the old build of ASP.NET MVC.
It would be interesting to able to execute an IHttpHandler during the execution of Web Api Controller with the lastes version (2.1).
The raison why I would ike to so is that I integrate Web Api with SharePoint 2013. It's work pretty well until that I would like to do SPContext.Current that is always null. After debugging, it seems that the PreExecuteHandler is never execute and never a chance for SharePoint to initialize the SPContext.Current.
However, if we have a IHttpHandler (haached.ashx), the context is no null.
This is why I'm asking if in the chaining of Web pi Controller Dispatcher, we can invoke internally the haacked.ashx and and up the request response with the IHttpHandler.

Léon

**Comment by Haacked** [comment]
Hi Leon, an `IHttpHandler` handles the request at the very end of the request. ASP.NET MVC and Web API are themselves effectively implemented as `IHttpHandlers`. So perhaps an `IHttpModule` is more appropriate?

In any case, I wouldn't know where to begin with integrating SharePoint. This seems like a question better suited to StackOverflow.
