### ISSUE TITLE
Custom Configuration Sections in 3 Easy Steps question

### ISSUE THREAD

**Issue by jcanning** [Haacked/feedback#54]
Are you able to create a tutorial for Custom Configuration Sections in 3 Easy Steps but using collections as well and likely more steps?

I have been searching the internet for ages trying to find the best examples. Yours was the first i got to to work. I have found Daniel Schroeder's Page and even though I don't get errors with his it just doesn't work. I feel you explained your set up pretty good and maybe hoped that you would reply to this feedback. :)

Thanks,
JAC

**Comment by Haacked** [comment]
Hi @jcanning I'm not sure I understand your question. Might be best to post it on StackOverflow and link back here.
