### ISSUE TITLE
The Dangers of Implementing Recurring Background Tasks In ASP.NET

### ISSUE THREAD

**Issue by abpatel** [Haacked/feedback#62]
Hey Phil,
I read your post on running background tasks in ASP.NET:
http://haacked.com/archive/2011/10/16/the-dangers-of-implementing-recurring-background-tasks-in-asp-net.aspx/

 I have a similar situation and would appreciate your input on this SO post:
http://stackoverflow.com/questions/24523330/long-running-background-tasks-using-asp-net

Thanks.

**Comment by Haacked** [comment]
It really depends on how long it'll take to finish processing the queue and how well you can recover if the app tears it down in the middle. If it has to be robust, use a scheduled task or some other background service like Azure workers.
