### ISSUE TITLE
Hello, how can i create new issue into the GitHub repository?

### ISSUE THREAD

**Issue by JoyLeeSoft** [Haacked/feedback#71]
I want to make automatic C# bug repoter.

If unhandled exception throws, i want to create issue automacally into the GitHub repository.

How can i do this?

Thanks.

**Comment by Haacked** [comment]
Install `Octokit.net` from NuGet and use that. http://www.nuget.org/packages/octokit

The [integration tests](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/IssuesClientTests.cs) have examples of creating an issue.
