### ISSUE TITLE
Let me Bing that for you site is obsolette

### ISSUE THREAD

**Issue by Mctk** [Haacked/feedback#74]
http://letmebingthatforyou.com/
This site was perfect when it was created, but in the meanwhile, Microsoft have changed the Bing logo.
Can you update this webpage with new Bing logo and search box?
I would be very grateful, because i want to use this page to teach some of my friends, who don't remember how to search :)

**Comment by Haacked** [comment]
Thanks for the heads up! Would you be interested in helping me do this? It's an open source project.

https://github.com/haacked/letmebingthatforyou
