### ISSUE TITLE
Invite Videocast :)

### ISSUE THREAD

**Issue by rodolfofadino** [Haacked/feedback#77]
Hello, my name is Rodolfo Fadino, I'm a developer. 
The reason of this issue is invite you to participate in one of our "Codificando Live" (a weekly videocast) for present something about GitHub.
This project is mantained by 3 MVP's (Rodolfo Fadino, Alexandre Tarifa and Diego Nogare) with no profit.
I also want say thank you for a Web Camp that I participated in Sao Paulo (many years ago).

Thank you

Rodolfo Fadino
@rodolfofadino
http://rodolfofadino.com.br/
http://live.codificando.net/

**Comment by Haacked** [comment]
Ok, let me check my schedule and get back to you. What days do you record?

**Comment by rodolfofadino** [comment]
We record every monday, but you can choose when is the best day to you

**Comment by haacked** [comment]
@rodolfofadino sorry this totally dropped off my radar. If this is still going on, I'd be happy to drop in. You can email me at my username at github.com.
