### ISSUE TITLE
Invitation to talk

### ISSUE THREAD

**Issue by decarufe** [Haacked/feedback#83]
Hi.

I would like to invite you to give a talk at msdevmtl.com user group in Montreal, Canada. Of course I can cover your expenses. 

Let me know if you are available between january and june 2015.

Best reagrds.

Eric De Carufel (eric@decarufel.net)

**Comment by Haacked** [comment]
Hi Eric, I'm sorry but I cannot do this this time. But do keep me in mind for the future.

**Comment by decarufe** [comment]
That all right.

If you want to come by anytime (it may be next fall) let me know. We will
cover your travel expense up to 1000$ and your stay here.

Hope to see you around in the next year.

Best regards.


On Fri, Jan 16, 2015 at 5:14 PM, Phil Haack <notifications@github.com>
wrote:

> Hi Eric, I'm sorry but I cannot do this this time. But do keep me in mind
> for the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Haacked/feedback/issues/83#issuecomment-70331249>.
>



-- 

*Eric* De Carufel <eric@decarufel.net> MVP C#

Cel : 514-554-3742
My profiles:  <http://www.facebook.com/#!/eric.decarufel> Facebook
<http://www.facebook.com/#!/eric.decarufel>
<http://ca.linkedin.com/in/edecarufel/fr> LinkedIn
<http://ca.linkedin.com/in/edecarufel/fr>  <http://blog.decarufel.net/> Blog
RSS <http://blog.decarufel.net/>  <http://twitter.com/decarufe> Twitter
<http://twitter.com/decarufe>
Chat : [image: Google Talk] edecarufel@pyxis-tech.com [image: MSN]
decarufe@hotmail.com
