### ISSUE TITLE
Model Bind A to List

### ISSUE THREAD

**Issue by starProjects** [Haacked/feedback#87]
Hi Phil,

Even though this is a 6 year post, still very useful for me but I have a question.

I did a multilevel bind using index:

`<input type="hidden" name="parent.Index" value="aaa" />`
`<input type="text" name="parent[aaa].Category" value="Cat1" />`
`<input type="text" name="parent[aaa].SubCategory" value="SubCat1" />`

`<input type="hidden" name="parent.Index" value="bbb" />`
`<input type="text" name="parent[bbb].Category" value="Cat2 />`
`<input type="text" name="parent[bbb].SubCategory" value="SubCat2" />`

`<input type="hidden" name="parent.Index" value="ccc" />`
`<input type="text" name="parent[ccc].Category" value="Cat3" />`
`<input type="text" name="parent[ccc].SubCategory" value="SubCat3" />`

`<input type="hidden" name="parent[ccc].products.Index" value="123" />`
`<input type="text" name="parent[ccc].products[123].Name" value="Chips" />`
`<input type="text" name="parent[ccc].products[123].Price" value="2.23" />`

The parent.index models are bond correctly but the parent[aaa].products.Index are not.

If I have 3 categories, aaa, bbb and ccc but for exemple only ccc has a product, it binds the product to aaa instead of ccc, in other words, any gap of products between categories it bind the product to the previous parent with no product

Thanks for any help, I have tried many forums but seems that no one have experienced this.

israelthieme@gmail.com

**Comment by Haacked** [comment]
Did you post this as a question to [StackOverflow](https://stackoverflow.com)? My memory of how this work is waning sadly. :cry: Post it there, add the link here, and maybe I can ping my friends over on the ASP.NET MVC team to take a look if nobody answers.
