### ISSUE TITLE
Auto updating a windows application

### ISSUE THREAD

**Issue by Beatles1692** [Haacked/feedback#89]
I was working on an auto-update mechanism for a windows application and I saw your auto-update open source project for web application and I read your [blog post](http://haacked.com/archive/2011/01/15/building-a-self-updating-site-using-nuget.aspx/)
I thought to my self "What a wonderful world!" :smiley: and  I decided to use the NuGet core library to do the job.
So first I want to thank you for your inspirational and great project :+1:  and second I'd like to have your opinion about using the same approach for a windows application.

**Comment by Haacked** [comment]
Check out https://github.com/Squirrel/Squirrel.Windows

It's based on NuGet and is for Windows apps.
