### ISSUE TITLE
Can I use your blog as a theme for my blog ?

### ISSUE THREAD

**Issue by mohamedkomalo** [Haacked/feedback#90]
I am creating a new blog and was searching for really minimal pure jykell themes that works directly with github. Your blog theme is amazing and simple, so I am asking if I can use it as a theme for my blog ?. I have seen the "Site design based on the Greyshade theme under the MIT license" at the footer but I still prefer to ask.

Thanks

**Comment by Haacked** [comment]
Sure! Just follow the terms of the license like I did. :)
