### ISSUE TITLE
GH contact for code review tool/process

### ISSUE THREAD

**Issue by Di-Ku** [Haacked/feedback#91]
Hi Phil,

A colleague from Google Cloud has some feedback / feature asks around code review tool/process in github. Would you care to suggest a contact he can talk to over email?

Thanks.
Dinesh
dck@google.com

**Comment by Di-Ku** [comment]
Never mind! Brad Abrams is already in touch with azimman & lee

**Comment by Haacked** [comment]
Perfect! Tell Brad I say hello. :smile:
