### ISSUE TITLE
I wrote a short book on Git and...

### ISSUE THREAD

**Issue by jesuswasrasta** [Haacked/feedback#92]
Hey Phil,  
  
My name is Ferdinando Santacroce, and I'm an humble C# developer and Git and GitHub user.
I'm writing a small book about Git and GitHub for newcomers, edited by __Packt__.

I thought to you for an honest opinion and, if you believe the book is good enough, for writing a small foreword. This is the link, the book is now in pre-sale: [Git Essentials](https://www.packtpub.com/application-development/git-essentials)

Do you have some spare time to read the final draft, when ready (next month)?
Your endorsement would make me very happy and proud, I'm following you since the days of Microsoft :)  

Thank you for your time,  
Nando

**Comment by Haacked** [comment]
Hi Fendinando,

I'm excited to hear that you're writing a book about Git and GitHub for
newcomers! I am incredibly busy and won't have time to read the final
draft. If there's a section in there about the GitHub for Windows and
GitHub for Mac apps, I certainly wouldn't mind reading those.

I only write forewords for books I've read and can thoroughly advocate.
However, if I read the sections on the desktop apps and like them, I could
provide a blurb. Is that ok?

Phil

**Comment by Haacked** [comment]
I closed the issue, but feel free to continue the conversation.

**Comment by jesuswasrasta** [comment]
Hi Phil.

Thank you for answering me, I really appreciate.
Unfortunately there will be not so much room for going deep into desktop applications like GitHub for Window and Mac; anyway I will send you that parts of the book, with no obligation for you to read or write anything.

Thank you so much for your time, keep the good work! :)
Ferdinando
