### ISSUE TITLE
Following up on GHfW

### ISSUE THREAD

**Issue by georgebearden** [Haacked/feedback#94]
Hi Phil, 

I wanted to follow up with you regarding the **GHfW** team.  I am currently developing desktop client software for both Windows and Mac using similar technologies and libraries that the **GHfW** team uses including:
* MS Visual Studio and Xamarin Studio
* .Net 4.5, C# and C++
* TDD, MVVM, REST, Rx and ReactiveUI

And if you have a moment, I would love to speak with you.  [Here is my resume :)](https://www.linkedin.com/in/georgebearden)

Best, 
George

**Comment by Haacked** [comment]
Hi George, sorry for the late response. Email me at phil@github.com
