### ISSUE TITLE
Git Essentials book blurb request

### ISSUE THREAD

**Issue by jesuswasrasta** [Haacked/feedback#95]
Good morning Phil.

I opened you an issue some weeks ago, requesting you to write the preface for the book I'm writing:
[Git Essentials](https://www.packtpub.com/application-development/git-essentials)  
You offered me to write a blurb if in the book I would reserve some room for GitHub for Windows; unfortunately editor left me a small chapter for writing about Git GUIs (7th chapter), so there is only a very humble paragraph about GitHub for Windows.  
  
Editor asks me to collect reviewers email, and then it will send to them the book preview for writing a blurb; if you have the time and will to read it, I'm asking you your email.  
Otherwise, if you don't want to provide your email, I can send you here a Dropbox link where to download the preview.  
  
If don't have time to waste, feel free to decline my offer, no problem :)
Thank you Phil, sorry for bothering you again :)  
  
Have a nice day,  
Nando

**Comment by Haacked** [comment]
Hi Nando,

I would really like to, but I've been incredibly busy lately and I don't want to promise something I can't deliver on. I'm sorry about that.

Phil

**Comment by Haacked** [comment]
p.s. don't hesitate to contact me for the 2nd edition. Perhaps the circumstances will be different.

**Comment by jesuswasrasta** [comment]
Hello Phil, thank you for answering me.
You implicitly said it will be a 2nd edition, I take this as a wish :D
In that case, you will hear about me again, for sure :P
Bye!
Nando :)
