### ISSUE TITLE
Dot Net Fringe

### ISSUE THREAD

**Issue by stgwilli** [Haacked/feedback#97]
I'm super excited about attending .NetFringe, but I am having problems purchasing a ticket. I checked with my bank and it isn't an issue with my card.

I sent an email to dotnetfringe@gmail.com but I haven't heard back yet. Any chance you could look into it? I didn't know who else to contact. :smile:

**Comment by stgwilli** [comment]
Thanks Phil! Troy setup a PayPal option on the payment form and that worked for me.

**Comment by Haacked** [comment]
![thumbs-up-computer-kid-gif](https://cloud.githubusercontent.com/assets/19977/6755832/24d5b102-cee3-11e4-8c8e-c6f210479f65.gif)

Glad it worked out!
