### ISSUE TITLE
Unnecessary query on ASP.NET  MVC

### ISSUE THREAD

**Issue by Leon-O** [Haacked/feedback#98]
Hi, I recently created a MVC 5 project and I want to give a try to Glimpse. When I look around on the SQL tab, I get 23 query, of those, 17 are duplicated!!! Those query are from the Identity Framework, so I want to know how, if it is possible, to caching or to remove those query.

Here is an screenshot of the Glimpse's window. I hope you can help me.

![unnecessary querys](https://cloud.githubusercontent.com/assets/4379316/6809550/6f4c8110-d231-11e4-866d-280c5f2d3230.PNG)

**Comment by Haacked** [comment]
Without seeing the code, I can't possibly know what's going on. But my psychic debugger tells me you're not using the `Include` extension method on your initial query to tell EF to include other tables and thus you have run into an N + 1 problem.

Check out the code here for an example.

https://github.com/Haacked/TournamentMaker/blob/master/TournamentMaker.Web/Controllers/HomeController.cs#L20-L24
