### ISSUE TITLE
Comment permalinks are outdated

### ISSUE THREAD

**Issue by TWiStErRob** [Haacked/feedback#99]
It seems that the comment links at [Why Can't Spec Writers Write...Specs?](http://haacked.com/archive/2007/03/07/Why_Cant_Spec_Writers_Write.Specs.aspx/) died because the format has been changed from
```
http://haacked.com/archive/2007/02/27/Why_Cant_Programmers._Read.aspx/#35757
```
to
```
http://haacked.com/archive/2007/02/27/Why_Cant_Programmers._Read.aspx/#comment-747518745
```
... hmm the ID is different, so you probably migrated the comments over to Disqus :)

**Comment by Haacked** [comment]
> hmm the ID is different, so you probably migrated the comments over to Disqus

[Yup!](http://haacked.com/archive/2012/12/25/migrating-comments-to-disqus.aspx/)

I just fixed up all the links. Thanks for the report! Guess I didn't expect people to actually click on links in 8 year old posts. I'm flattered. :smile:

**Comment by TWiStErRob** [comment]
You know if I read a good article I check the related stuff out, and you have a lot of good resources/references lying around in your posts. :)
